### ISSUE TITLE
Sharing the simulation data

### ISSUE THREAD

**Issue by 4turkuaz** [hcemeljic/Diesel-Generators-Simulator#1]
Hello, good work. I'm curious about the data you've used for simulation. Is there any chance to share it? Thanks in advance.

**Comment by hcemeljic** [comment]
Hi, thank you for your comment. May I ask how did you find this repo? Cheers.

**Comment by 4turkuaz** [comment]
By simply searching "diesel generators" in GitHub search. I'm currently working on an academic project in which I lack of some data. That's why I'm asking you.

**Comment by hcemeljic** [comment]
Thank you. Unfortunately I cannot provide any information on the recorded
data. I am sorry.

**Comment by 4turkuaz** [comment]
Thanks anyway
